export interface TemplateCard {
  id: string;
  name: string;
  description: string;
  category: string;
  age: string;
  accent: 'green' | 'blue' | 'orange' | 'purple';
}

export const AGENT_TEMPLATES: TemplateCard[] = [
  {
    id: 'product-adoption-specialist',
    name: 'Product Adoption Specialist',
    description: 'Analyzes product usage to boost adoption rates with tailored recommendations.',
    category: 'Onboarding',
    age: '1m ago',
    accent: 'green',
  },
  {
    id: 'payroll-compliance-agent',
    name: 'Payroll Compliance Agent',
    description: 'Monitors payroll data to ensure compliance with local labor laws and tax regulations.',
    category: 'Payroll',
    age: '1h ago',
    accent: 'blue',
  },
  {
    id: 'employee-engagement-agent',
    name: 'Employee Engagement Agent',
    description: 'Analyzes employee survey feedback to provide insights on engagement levels.',
    category: 'Employee Interaction',
    age: '1h ago',
    accent: 'orange',
  },
  {
    id: 'learning-and-development-advisor',
    name: 'Learning and Development Advisor',
    description: 'Tracks employee training progress and suggests personalized learning paths.',
    category: 'Skill Development',
    age: '1h ago',
    accent: 'orange',
  },
  {
    id: 'attendance-management-agent',
    name: 'Attendance Management Agent',
    description: 'Analyzes attendance patterns to identify anomalies and recommend policy adjustments.',
    category: 'Employee',
    age: '1h ago',
    accent: 'purple',
  },
  {
    id: 'performance-review-agent',
    name: 'Performance Review Agent',
    description: 'Automates collection and analysis of performance feedback for continuous improvement.',
    category: 'Benefits',
    age: '1h ago',
    accent: 'blue',
  },
  {
    id: 'recruitment-analytics-agent',
    name: 'Recruitment Analytics Agent',
    description: 'Evaluates hiring metrics to optimize recruitment strategies and improve quality.',
    category: 'Talent Acquisition',
    age: '1h ago',
    accent: 'orange',
  },
  {
    id: 'payroll-compliance-checker',
    name: 'Payroll Compliance Checker',
    description: 'Monitors payroll data to ensure adherence to legal standards and flag discrepancies.',
    category: 'Compensation',
    age: '1h ago',
    accent: 'purple',
  },
  {
    id: 'employee-engagement-bot',
    name: 'Employee Engagement Bot',
    description: 'Gathers real-time feedback to enhance workplace satisfaction and reduce turnover.',
    category: 'Workplace Experience',
    age: '1h ago',
    accent: 'blue',
  },
  {
    id: 'onboarding-experience-agent',
    name: 'Onboarding Experience Agent',
    description: 'Guides new hires through orientation and tracks integration progress.',
    category: 'Employee Lifecycle',
    age: '1h ago',
    accent: 'orange',
  },
  {
    id: 'time-off-optimization-agent',
    name: 'Time-Off Optimization Agent',
    description: 'Analyzes leave patterns to balance workforce availability and employee wellness.',
    category: 'Attendance',
    age: '1h ago',
    accent: 'purple',
  },
  {
    id: 'compensation-benchmarking-agent',
    name: 'Compensation Benchmarking Agent',
    description: 'Compares salaries within industry standards to recommend fair pay adjustments.',
    category: 'Compensation',
    age: '1h ago',
    accent: 'blue',
  },
  {
    id: 'succession-planning-advisor',
    name: 'Succession Planning Advisor',
    description: 'Identifies potential leaders by analyzing performance and career trajectories.',
    category: 'Talent Management',
    age: '1h ago',
    accent: 'orange',
  },
  {
    id: 'workforce-diversity-tracker',
    name: 'Workforce Diversity Tracker',
    description: 'Monitors diversity metrics and suggests initiatives to improve inclusion.',
    category: 'HR Analytics',
    age: '1h ago',
    accent: 'purple',
  },
  {
    id: 'wellness-program-coordinator',
    name: 'Wellness Program Coordinator',
    description: 'Recommends health initiatives based on employee wellbeing data.',
    category: 'Employee Wellness',
    age: '1h ago',
    accent: 'blue',
  },
  {
    id: 'internal-mobility-coach',
    name: 'Internal Mobility Coach',
    description: 'Surfaces role opportunities based on skills, aspirations, and manager feedback.',
    category: 'Mobility',
    age: '1h ago',
    accent: 'green',
  },
  {
    id: 'attrition-risk-analyst',
    name: 'Attrition Risk Analyst',
    description: 'Identifies retention signals from engagement, attendance, and manager patterns.',
    category: 'Retention',
    age: '1h ago',
    accent: 'orange',
  },
  {
    id: 'benefits-optimization-agent',
    name: 'Benefits Optimization Agent',
    description: 'Benchmarks benefits usage and recommends policy improvements for utilization.',
    category: 'Benefits',
    age: '1h ago',
    accent: 'blue',
  },
  {
    id: 'goal-alignment-agent',
    name: 'Goal Alignment Agent',
    description: 'Maps goals across teams and highlights dependency conflicts before reviews.',
    category: 'Goals',
    age: '1h ago',
    accent: 'purple',
  },
  {
    id: 'expense-audit-agent',
    name: 'Expense Audit Agent',
    description: 'Flags claim anomalies by policy, amount patterns, and missing documents.',
    category: 'Finance',
    age: '1h ago',
    accent: 'green',
  },
  {
    id: 'knowledge-retrieval-agent',
    name: 'Knowledge Retrieval Agent',
    description: 'Indexes playbooks and SOPs to answer policy and process questions.',
    category: 'Knowledge',
    age: '1h ago',
    accent: 'blue',
  },
  {
    id: 'manager-copilot-agent',
    name: 'Manager Copilot Agent',
    description: 'Prepares manager briefings with team trends, talking points, and coaching prompts.',
    category: 'Leadership',
    age: '1h ago',
    accent: 'purple',
  },
  {
    id: 'sentiment-watch-agent',
    name: 'Sentiment Watch Agent',
    description: 'Monitors pulse feedback and flags sentiment shifts by department.',
    category: 'Engagement',
    age: '1h ago',
    accent: 'orange',
  },
  {
    id: 'shift-forecasting-agent',
    name: 'Shift Forecasting Agent',
    description: 'Predicts workforce coverage gaps and proposes optimized schedules.',
    category: 'Scheduling',
    age: '1h ago',
    accent: 'green',
  },
  {
    id: 'compliance-narrator-agent',
    name: 'Compliance Narrator Agent',
    description: 'Summarizes regulatory changes and converts updates into task-ready guidance.',
    category: 'Compliance',
    age: '1h ago',
    accent: 'blue',
  },
];

export function findAgentTemplate(templateId: string | null): TemplateCard {
  return AGENT_TEMPLATES.find((template) => template.id === templateId) ?? AGENT_TEMPLATES[0];
}
