import { TraceCase, TraceDebugResult, TraceStep } from './trace.types';

type TraceSeed = Omit<TraceStep, 'responseId'>;

const baseTimestamp = 'May 27, 17:35:28.082';
const toolTimestamp = 'May 27, 12:21:02.268';

function createStep(responseId: string, seed: TraceSeed): TraceStep {
  return { ...seed, responseId };
}

function createCase(
  id: string,
  label: string,
  scenario: string,
  samplePrompt: string,
  assistantResponse: string,
  steps: TraceSeed[],
): TraceCase {
  return {
    id,
    label,
    scenario,
    samplePrompt,
    assistantResponse,
    steps: steps.map((step) => createStep(id, step)),
  };
}

export const TRACE_CASES: TraceCase[] = [
  createCase(
    'simple-llm-response',
    'Simple LLM Response',
    'Agent answers a basic question with only the model.',
    'What is onboarding?',
    'Onboarding is the guided process of helping a new hire complete joining steps, understand policies, and become productive in the organization.',
    [
      {
        id: 'simple-llm-1',
        sequence: 1,
        type: 'llm_call',
        title: 'LLM Call',
        subtitle: 'Iteration 1',
        summary: 'The agent sent the user question to the selected model and generated a direct explanation.',
        status: 'success',
        timestamp: baseTimestamp,
        durationMs: 410,
        model: 'claude-sonnet-4-6',
        inputTokens: 3,
        outputTokens: 87,
        totalTokens: 90,
        rawLog: { input_tokens: 3, output_tokens: 87, model: 'claude-sonnet-4-6' },
      },
      {
        id: 'simple-final',
        sequence: 2,
        type: 'final_response',
        title: 'Final Response',
        subtitle: 'Response Sent',
        summary: 'The final answer was sent back to the chat.',
        status: 'success',
        timestamp: baseTimestamp,
        durationMs: 18,
        output: 'Onboarding is the guided process of helping a new hire complete joining steps, understand policies, and become productive.',
        rawLog: { response_ready: true, channel: 'agent_chat' },
      },
    ],
  ),
  createCase(
    'tool-success',
    'Tool Call Success',
    'Agent updates onboarding details and confirms success.',
    'How can I onboard a new employee and setup a buddy?',
    'I can help with that. I updated the onboarding criteria and included buddy setup for the candidate.',
    [
      {
        id: 'tool-success-llm-1',
        sequence: 1,
        type: 'llm_call',
        title: 'LLM Call',
        subtitle: 'Iteration 1',
        summary: 'The agent interpreted the request and decided to call the onboarding update tool.',
        status: 'success',
        timestamp: baseTimestamp,
        durationMs: 380,
        model: 'claude-sonnet-4-6',
        inputTokens: 106,
        outputTokens: 30,
        totalTokens: 136,
        rawLog: { input_tokens: 106, output_tokens: 30, model: 'claude-sonnet-4-6' },
      },
      {
        id: 'tool-success-call',
        sequence: 2,
        type: 'tool_call',
        title: 'Update Onboarding Details',
        subtitle: 'Call',
        summary: 'The agent called the onboarding workflow tool with candidate and buddy setup details.',
        status: 'running',
        timestamp: toolTimestamp,
        durationMs: 14,
        input: { job_id: '12323', candidate_name: 'Amit Sharma', buddy_required: true },
        rawLog: { tool: 'update_onboarding_details', method: 'POST', request_id: 'req_12323' },
      },
      {
        id: 'tool-success-result',
        sequence: 3,
        type: 'tool_result',
        title: 'Update Onboarding Details',
        subtitle: 'Result - 37ms',
        summary: 'The tool confirmed that the onboarding criteria were updated successfully.',
        status: 'success',
        timestamp: toolTimestamp,
        durationMs: 37,
        output: 'Updated criteria successfully',
        rawLog: { status: 200, message: 'Updated criteria successfully' },
      },
      {
        id: 'tool-success-llm-2',
        sequence: 4,
        type: 'llm_call',
        title: 'LLM Call',
        subtitle: 'Iteration 2',
        summary: 'The model prepared the final user-facing confirmation from the tool result.',
        status: 'success',
        timestamp: baseTimestamp,
        durationMs: 290,
        model: 'claude-sonnet-4-6',
        inputTokens: 118,
        outputTokens: 34,
        totalTokens: 152,
        rawLog: { input_tokens: 118, output_tokens: 34, model: 'claude-sonnet-4-6' },
      },
      {
        id: 'tool-success-final',
        sequence: 5,
        type: 'final_response',
        title: 'Final Response',
        subtitle: 'Response Sent',
        summary: 'The user was told that onboarding details and buddy setup were updated.',
        status: 'success',
        timestamp: baseTimestamp,
        output: 'I updated the onboarding criteria and included buddy setup for the candidate.',
      },
    ],
  ),
  createCase(
    'missing-input',
    'Missing Required Input',
    'Agent asks for resume and required candidate data before proceeding.',
    'Onboard this candidate.',
    'Ok, let me know what are the candidate details along with the resume attached so that I can attach the correct details into the system.',
    [
      {
        id: 'missing-llm-1',
        sequence: 1,
        type: 'llm_call',
        title: 'LLM Call',
        subtitle: 'Iteration 1',
        summary: 'The agent reviewed the request and found it needed candidate data before taking action.',
        status: 'success',
        timestamp: baseTimestamp,
        durationMs: 244,
        model: 'claude-sonnet-4-6',
        inputTokens: 42,
        outputTokens: 28,
        totalTokens: 70,
        rawLog: { input_tokens: 42, output_tokens: 28, model: 'claude-sonnet-4-6' },
      },
      {
        id: 'missing-validation',
        sequence: 2,
        type: 'validation',
        title: 'Validation Check',
        subtitle: 'Required Inputs',
        summary: 'Required fields were checked before calling the onboarding tool.',
        status: 'success',
        timestamp: toolTimestamp,
        durationMs: 16,
        output: { missing_fields: ['candidate_resume', 'joining_date', 'role'], can_continue: false },
        rawLog: { validator: 'onboarding_required_fields', can_continue: false },
      },
      {
        id: 'missing-detected',
        sequence: 3,
        type: 'error',
        title: 'Missing Input Detected',
        subtitle: 'Needs User Input',
        summary: 'The agent stopped before tool execution because candidate details were incomplete.',
        status: 'skipped',
        timestamp: toolTimestamp,
        output: { missing_fields: ['candidate_resume', 'joining_date', 'role'] },
      },
      {
        id: 'missing-final',
        sequence: 4,
        type: 'final_response',
        title: 'Final Response',
        subtitle: 'Clarification Requested',
        summary: 'The agent asked the user to provide the missing candidate details and resume.',
        status: 'success',
        timestamp: baseTimestamp,
        output: 'Share the candidate resume, joining date, and role so I can continue.',
      },
    ],
  ),
  createCase(
    'tool-failure',
    'Tool Failure',
    'Agent calls an onboarding API and receives a timeout.',
    'Update onboarding for Amit but the API is down.',
    'I understood the onboarding update, but the connected onboarding API timed out. Retry or check the onboarding API connection.',
    [
      {
        id: 'failure-llm-1',
        sequence: 1,
        type: 'llm_call',
        title: 'LLM Call',
        subtitle: 'Iteration 1',
        summary: 'The agent understood the request and prepared a tool call.',
        status: 'success',
        timestamp: baseTimestamp,
        durationMs: 322,
        model: 'claude-sonnet-4-6',
        inputTokens: 88,
        outputTokens: 22,
        totalTokens: 110,
        rawLog: { input_tokens: 88, output_tokens: 22, model: 'claude-sonnet-4-6' },
      },
      {
        id: 'failure-call',
        sequence: 2,
        type: 'tool_call',
        title: 'Update Onboarding Details',
        subtitle: 'Call',
        summary: 'The onboarding tool was called with the provided candidate details.',
        status: 'running',
        timestamp: toolTimestamp,
        input: { job_id: '12323', candidate_name: 'Amit Sharma', buddy_required: true },
      },
      {
        id: 'failure-error',
        sequence: 3,
        type: 'error',
        title: 'Update Onboarding Details',
        subtitle: 'Failed',
        summary: 'The onboarding API did not respond in time.',
        status: 'failed',
        timestamp: toolTimestamp,
        durationMs: 30000,
        error: { code: 'API_TIMEOUT', message: 'Onboarding API did not respond within 30 seconds' },
        rawLog: { status: 504, code: 'API_TIMEOUT', retryable: true },
      },
      {
        id: 'failure-handling',
        sequence: 4,
        type: 'error',
        title: 'Error Handling',
        subtitle: 'User Safe Message',
        summary: 'The agent converted the tool failure into a clear retry recommendation.',
        status: 'success',
        timestamp: baseTimestamp,
        output: { user_message: 'Retry or check the onboarding API connection.' },
      },
      {
        id: 'failure-final',
        sequence: 5,
        type: 'final_response',
        title: 'Final Response',
        subtitle: 'Failure Explained',
        summary: 'The agent explained that the failure happened at the API tool call.',
        status: 'success',
        timestamp: baseTimestamp,
        output: 'The onboarding API timed out. Retry or check the API connection.',
      },
    ],
  ),
  createCase(
    'retry-flow',
    'Retry Flow',
    'Tool call fails once, then succeeds after retry.',
    'Retry onboarding update for Amit.',
    'The first attempt failed, but the retry succeeded. Onboarding details are now updated.',
    [
      {
        id: 'retry-llm-1',
        sequence: 1,
        type: 'llm_call',
        title: 'LLM Call',
        subtitle: 'Iteration 1',
        summary: 'The agent prepared the onboarding update and identified the tool to call.',
        status: 'success',
        timestamp: baseTimestamp,
        model: 'claude-sonnet-4-6',
        inputTokens: 96,
        outputTokens: 28,
        totalTokens: 124,
        rawLog: { input_tokens: 96, output_tokens: 28, model: 'claude-sonnet-4-6' },
      },
      {
        id: 'retry-call',
        sequence: 2,
        type: 'tool_call',
        title: 'Update Onboarding Details',
        subtitle: 'Call',
        summary: 'The first tool call was sent to the onboarding API.',
        status: 'running',
        timestamp: toolTimestamp,
        input: { job_id: '12323', candidate_name: 'Amit Sharma', buddy_required: true },
      },
      {
        id: 'retry-failed',
        sequence: 3,
        type: 'error',
        title: 'Update Onboarding Details',
        subtitle: 'Failed',
        summary: 'The first tool attempt failed because the API gateway timed out.',
        status: 'failed',
        timestamp: toolTimestamp,
        error: { code: 'GATEWAY_TIMEOUT', message: 'Temporary API gateway timeout' },
      },
      {
        id: 'retry-attempt',
        sequence: 4,
        type: 'retry',
        title: 'Retry Attempt 1',
        subtitle: 'Automatic Retry',
        summary: 'The agent retried the same tool call because the failure was retryable.',
        status: 'retried',
        timestamp: toolTimestamp,
        retry: { attempt: 1, maxAttempts: 2, reason: 'Gateway timeout is retryable' },
      },
      {
        id: 'retry-result',
        sequence: 5,
        type: 'tool_result',
        title: 'Update Onboarding Details',
        subtitle: 'Result - 82ms',
        summary: 'The retry succeeded and the onboarding details were updated.',
        status: 'success',
        timestamp: toolTimestamp,
        durationMs: 82,
        output: 'Updated criteria successfully',
      },
      {
        id: 'retry-llm-2',
        sequence: 6,
        type: 'llm_call',
        title: 'LLM Call',
        subtitle: 'Iteration 2',
        summary: 'The model summarized the retry outcome for the user.',
        status: 'success',
        timestamp: baseTimestamp,
        model: 'claude-sonnet-4-6',
        inputTokens: 142,
        outputTokens: 35,
        totalTokens: 177,
        rawLog: { input_tokens: 142, output_tokens: 35, model: 'claude-sonnet-4-6' },
      },
      {
        id: 'retry-final',
        sequence: 7,
        type: 'final_response',
        title: 'Final Response',
        subtitle: 'Retry Successful',
        summary: 'The final answer told the user that the retry succeeded.',
        status: 'success',
        timestamp: baseTimestamp,
        output: 'The first attempt failed, but the retry succeeded.',
      },
    ],
  ),
  createCase(
    'file-resume-parse',
    'File Attachment Resume Parse',
    'Agent parses resume details before onboarding update.',
    'Create onboarding details from this resume.',
    'I extracted the candidate details from the resume and prepared the onboarding setup.',
    [
      {
        id: 'file-parse',
        sequence: 1,
        type: 'file_parse',
        title: 'File Parse',
        subtitle: 'Resume.pdf',
        summary: 'The resume attachment was parsed before validation.',
        status: 'success',
        timestamp: baseTimestamp,
        durationMs: 620,
        output: { candidate_name: 'Amit Sharma', email: 'amit@example.com', phone: '+91 9876543210', experience: '5 years', role: 'Product Designer' },
      },
      {
        id: 'file-extract',
        sequence: 2,
        type: 'data_lookup',
        title: 'Extract Candidate Details',
        subtitle: 'Parsed Resume Data',
        summary: 'Key candidate fields were normalized for the onboarding tool.',
        status: 'success',
        timestamp: baseTimestamp,
        output: { candidate_name: 'Amit Sharma', role: 'Product Designer', experience: '5 years' },
      },
      {
        id: 'file-validation',
        sequence: 3,
        type: 'validation',
        title: 'Validation Check',
        subtitle: 'Required Inputs',
        summary: 'Candidate details were complete enough to continue.',
        status: 'success',
        timestamp: toolTimestamp,
        output: { missing_fields: [], can_continue: true },
      },
      {
        id: 'file-tool-call',
        sequence: 4,
        type: 'tool_call',
        title: 'Update Onboarding Details',
        subtitle: 'Call',
        summary: 'The parsed candidate details were sent to the onboarding tool.',
        status: 'running',
        timestamp: toolTimestamp,
        input: { candidate_name: 'Amit Sharma', email: 'amit@example.com', role: 'Product Designer' },
      },
      {
        id: 'file-tool-result',
        sequence: 5,
        type: 'tool_result',
        title: 'Update Onboarding Details',
        subtitle: 'Result - 68ms',
        summary: 'The onboarding details were created from the parsed resume data.',
        status: 'success',
        timestamp: toolTimestamp,
        durationMs: 68,
        output: 'Onboarding details created successfully',
      },
      {
        id: 'file-final',
        sequence: 6,
        type: 'final_response',
        title: 'Final Response',
        subtitle: 'Response Sent',
        summary: 'The agent confirmed that resume details were extracted and applied.',
        status: 'success',
        timestamp: baseTimestamp,
        output: 'I extracted the candidate details from the resume and prepared the onboarding setup.',
      },
    ],
  ),
  createCase(
    'conditional-branch',
    'Conditional Branch',
    'Agent checks whether buddy setup is required.',
    'Create onboarding and assign a buddy if needed.',
    'Buddy setup was required, so I assigned a buddy and updated onboarding details.',
    [
      {
        id: 'condition-llm-1',
        sequence: 1,
        type: 'llm_call',
        title: 'LLM Call',
        subtitle: 'Iteration 1',
        summary: 'The agent prepared a condition check for buddy assignment.',
        status: 'success',
        timestamp: baseTimestamp,
        model: 'claude-sonnet-4-6',
        inputTokens: 76,
        outputTokens: 24,
        totalTokens: 100,
        rawLog: { input_tokens: 76, output_tokens: 24, model: 'claude-sonnet-4-6' },
      },
      {
        id: 'condition-check',
        sequence: 2,
        type: 'condition_check',
        title: 'Condition Check: Buddy Required?',
        subtitle: 'Branch Result',
        summary: 'The condition evaluated true, so the buddy assignment branch was selected.',
        status: 'success',
        timestamp: toolTimestamp,
        output: { condition: 'buddy_required === true', result: true },
      },
      {
        id: 'condition-assign-call',
        sequence: 3,
        type: 'tool_call',
        title: 'Assign Buddy',
        subtitle: 'Call',
        summary: 'The agent called the buddy assignment tool.',
        status: 'running',
        timestamp: toolTimestamp,
        input: { candidate_name: 'Amit Sharma', buddy_required: true },
      },
      {
        id: 'condition-assign-result',
        sequence: 4,
        type: 'tool_result',
        title: 'Assign Buddy',
        subtitle: 'Result - 41ms',
        summary: 'A buddy was assigned for the new employee.',
        status: 'success',
        timestamp: toolTimestamp,
        output: { buddy_name: 'Neha Verma', buddy_id: 'EMP-2041' },
      },
      {
        id: 'condition-update-result',
        sequence: 5,
        type: 'tool_result',
        title: 'Update Onboarding Details',
        subtitle: 'Result - 52ms',
        summary: 'The onboarding record was updated with buddy details.',
        status: 'success',
        timestamp: toolTimestamp,
        output: 'Updated onboarding details with assigned buddy',
      },
      {
        id: 'condition-final',
        sequence: 6,
        type: 'final_response',
        title: 'Final Response',
        subtitle: 'Response Sent',
        summary: 'The agent confirmed that buddy setup was completed.',
        status: 'success',
        timestamp: baseTimestamp,
        output: 'Buddy setup was required, so I assigned a buddy and updated onboarding details.',
      },
    ],
  ),
  createCase(
    'human-approval',
    'Human Approval Required',
    'Agent pauses until HR approval is provided.',
    'Complete onboarding that requires HR approval.',
    'This onboarding action needs HR Admin approval before I can continue.',
    [
      {
        id: 'approval-llm-1',
        sequence: 1,
        type: 'llm_call',
        title: 'LLM Call',
        subtitle: 'Iteration 1',
        summary: 'The agent identified that the requested action may require approval.',
        status: 'success',
        timestamp: baseTimestamp,
        model: 'claude-sonnet-4-6',
        inputTokens: 65,
        outputTokens: 26,
        totalTokens: 91,
      },
      {
        id: 'approval-policy',
        sequence: 2,
        type: 'validation',
        title: 'Policy Check',
        subtitle: 'HR Governance',
        summary: 'The policy check found that HR Admin approval is required.',
        status: 'success',
        timestamp: toolTimestamp,
        output: { approval_required: true, approver: 'HR Admin' },
      },
      {
        id: 'approval-required',
        sequence: 3,
        type: 'human_approval',
        title: 'Human Approval Required',
        subtitle: 'HR Admin',
        summary: 'The workflow is waiting for HR Admin approval.',
        status: 'waiting',
        timestamp: toolTimestamp,
        output: { approver: 'HR Admin', status: 'waiting' },
      },
      {
        id: 'approval-waiting',
        sequence: 4,
        type: 'human_approval',
        title: 'Waiting for Approval',
        subtitle: 'Paused',
        summary: 'The agent cannot complete the action until approval is received.',
        status: 'waiting',
        timestamp: toolTimestamp,
        output: 'Approval required from HR Admin',
      },
    ],
  ),
  createCase(
    'high-token-usage',
    'High Token Usage Warning',
    'Knowledge search returns large context and increases model tokens.',
    'Summarize every onboarding policy and related FAQ.',
    'I summarized the onboarding policy set, but this answer used a high amount of context from knowledge search.',
    [
      {
        id: 'token-llm-1',
        sequence: 1,
        type: 'llm_call',
        title: 'LLM Call',
        subtitle: 'Iteration 1',
        summary: 'The agent planned a knowledge search because the question required policy context.',
        status: 'success',
        timestamp: baseTimestamp,
        model: 'claude-sonnet-4-6',
        inputTokens: 420,
        outputTokens: 64,
        totalTokens: 484,
      },
      {
        id: 'token-knowledge-search',
        sequence: 2,
        type: 'data_lookup',
        title: 'Knowledge Search',
        subtitle: 'Large Context',
        summary: 'Knowledge search returned a large policy context, which increased downstream token usage.',
        status: 'success',
        timestamp: toolTimestamp,
        durationMs: 380,
        output: { sources: 18, chunks: 42, estimated_tokens: 4800 },
      },
      {
        id: 'token-llm-2',
        sequence: 3,
        type: 'llm_call',
        title: 'LLM Call',
        subtitle: 'Iteration 2',
        summary: 'This model call used high tokens because the knowledge context was broad.',
        status: 'success',
        timestamp: baseTimestamp,
        model: 'claude-sonnet-4-6',
        inputTokens: 5200,
        outputTokens: 640,
        totalTokens: 5840,
        rawLog: { input_tokens: 5200, output_tokens: 640, model: 'claude-sonnet-4-6', warning: 'high_context_usage' },
      },
      {
        id: 'token-final',
        sequence: 4,
        type: 'final_response',
        title: 'Final Response',
        subtitle: 'High Token Notice',
        summary: 'The final response was generated, but Copilot recommends narrowing the knowledge source next time.',
        status: 'success',
        timestamp: baseTimestamp,
        output: 'This response used high tokens because knowledge search returned large context. Consider narrowing the source or summarizing before final response.',
      },
    ],
  ),
];

export function getTraceCase(caseId: string): TraceCase {
  return TRACE_CASES.find((traceCase) => traceCase.id === caseId) ?? TRACE_CASES[0];
}

export function cloneTraceStepsForResponse(caseId: string, responseId: string): TraceStep[] {
  return getTraceCase(caseId).steps.map((step) => ({
    ...step,
    id: `${responseId}-${step.sequence}`,
    responseId,
  }));
}

export function pickTraceCaseIdForPrompt(prompt: string): string {
  const query = prompt.toLowerCase();

  if (query.includes('approval') || query.includes('approve')) return 'human-approval';
  if (query.includes('retry')) return 'retry-flow';
  if (query.includes('fail') || query.includes('timeout') || query.includes('api')) return 'tool-failure';
  if (query.includes('resume') || query.includes('attach') || query.includes('file')) return 'file-resume-parse';
  if (query.includes('token') || query.includes('policy') || query.includes('summarize')) return 'high-token-usage';
  if (query.includes('buddy') || query.includes('setup')) return 'tool-success';
  if (query.includes('if') || query.includes('condition')) return 'conditional-branch';
  if (query.includes('candidate') || query.includes('onboard')) return 'missing-input';

  return 'simple-llm-response';
}

export function buildTraceDebugResult(steps: TraceStep[], selectedStep?: TraceStep): TraceDebugResult {
  const failedStep = selectedStep?.status === 'failed' ? selectedStep : steps.find((step) => step.status === 'failed');
  const waitingStep = selectedStep?.status === 'waiting' ? selectedStep : steps.find((step) => step.status === 'waiting');
  const highTokenStep = selectedStep?.totalTokens && selectedStep.totalTokens > 3000
    ? selectedStep
    : steps.find((step) => (step.totalTokens ?? 0) > 3000);
  const contextStep = selectedStep ?? failedStep ?? waitingStep ?? highTokenStep ?? steps[0];
  const contextLabel = selectedStep ? contextStep.title : 'Full Trace';

  if (failedStep) {
    return {
      title: selectedStep ? `Debug: ${contextStep.title}` : 'Debug Full Trace',
      contextLabel,
      happened: 'The agent understood the request and started the expected workflow.',
      issue: `The issue happened at ${failedStep.title}.`,
      reason: failedStep.error?.message ?? 'The connected action failed before the workflow could finish.',
      fix: 'Retry the action once. If it fails again, check the tool connection and API health.',
      nextAction: 'Retry or contact the workflow admin if the API keeps timing out.',
    };
  }

  if (waitingStep) {
    return {
      title: selectedStep ? `Debug: ${contextStep.title}` : 'Debug Full Trace',
      contextLabel,
      happened: 'The agent reached a governed workflow step.',
      issue: `The workflow is paused at ${waitingStep.title}.`,
      reason: 'The policy check requires HR Admin approval before the agent can continue.',
      fix: 'Ask the approver to approve the request, then resume the workflow.',
      nextAction: 'Wait for approval or contact the HR Admin.',
    };
  }

  if (highTokenStep) {
    return {
      title: selectedStep ? `Debug: ${contextStep.title}` : 'Debug Full Trace',
      contextLabel,
      happened: 'The agent searched a broad knowledge context before answering.',
      issue: `${highTokenStep.title} used ${highTokenStep.totalTokens} total tokens.`,
      reason: 'Knowledge search returned large context and the model processed most of it.',
      fix: 'Narrow the knowledge source, filter by policy type, or summarize retrieved context before the final response.',
      nextAction: 'Edit the prompt or reduce retrieval scope before retrying.',
    };
  }

  return {
    title: selectedStep ? `Debug: ${contextStep.title}` : 'Debug Full Trace',
    contextLabel,
    happened: selectedStep ? contextStep.summary ?? 'This step completed successfully.' : 'All trace steps completed without blocking errors.',
    issue: 'No failure was detected in this trace.',
    reason: 'The agent used the expected model and action path for this request.',
    fix: 'No fix is required. You can inspect raw logs if you need deeper validation.',
    nextAction: 'Continue, or copy the trace if you need to share it with an admin.',
  };
}
